In [94]:
import torch
import numpy as np

print(torch.__version__)

1.12.1


# Tensor Basics

In [6]:
x = torch.empty(3, 2)
x

tensor([[6.8664e-44, 8.1275e-44],
        [7.4269e-44, 7.2868e-44],
        [8.1275e-44, 7.0065e-44]])

In [4]:
y = torch.empty(2, 3)
y

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [16]:
z = torch.ones(4, 3, dtype=torch.double)
z

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)

In [14]:
k = torch.zeros(3 ,4, dtype=torch.int)
k

tensor([[0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0]], dtype=torch.int32)

In [15]:
k.dtype

torch.int32

In [18]:
x.size()

torch.Size([3, 2])

In [21]:
# Filled in with values
f = torch.tensor([2.2, 5.2, 3, 4])
f

tensor([2.2000, 5.2000, 3.0000, 4.0000])

In [41]:
# Tensors additin 
q = torch.rand(2,2)
w = torch.rand(2,2)

In [40]:
print(w)
print(q)

tensor([[0.4873, 0.0473],
        [0.0293, 0.5337]])
tensor([[0.1024, 0.3141],
        [0.5061, 0.9812]])


In [43]:
e = w + q
e

tensor([[1.5733, 1.7646],
        [0.6869, 1.2649]])

In [85]:
# More run bigger numbers
w.add_(q)
w

tensor([[25.3528, 26.9727],
        [13.9793, 24.9808]])

In [90]:
r = torch.sub(q, w)
r

tensor([[-24.7728, -26.3579],
        [-13.6551, -24.4024]])

In [92]:
r = torch.mul(q, w)
r

tensor([[14.7043, 16.5837],
        [ 4.5321, 14.4498]])

In [96]:
r = torch.div(q,w)
r

tensor([[0.0229, 0.0228],
        [0.0232, 0.0232]])

In [100]:
x = torch.rand(5, 3)
x

tensor([[0.5138, 0.5753, 0.5932],
        [0.3660, 0.5026, 0.0282],
        [0.1634, 0.0134, 0.7943],
        [0.5737, 0.5932, 0.0139],
        [0.6662, 0.3841, 0.8565]])

In [102]:
x[0,0]

tensor(0.5138)

In [103]:
x[1,1]

tensor(0.5026)

In [104]:
x[2,2]

tensor(0.7943)

In [107]:
x[3,1]

tensor(0.5932)

In [109]:
x[1,2]

tensor(0.0282)

In [114]:
x[1:4, 2]

tensor([0.0282, 0.7943, 0.0139])

### Reshaping

In [118]:
x = torch.rand(4, 4)
x

y = x.view(16)

In [120]:
y

tensor([0.3745, 0.5367, 0.0789, 0.2334, 0.8085, 0.9778, 0.2563, 0.0011, 0.2818,
        0.2788, 0.5581, 0.3802, 0.1703, 0.3691, 0.3024, 0.3907])

In [119]:
x

tensor([[0.3745, 0.5367, 0.0789, 0.2334],
        [0.8085, 0.9778, 0.2563, 0.0011],
        [0.2818, 0.2788, 0.5581, 0.3802],
        [0.1703, 0.3691, 0.3024, 0.3907]])

In [121]:
y = x.view(2, 8)

In [123]:
y.size()

torch.Size([2, 8])

### Converting Numpy to Tensor 

In [127]:
a = torch.ones(5)
a

tensor([1., 1., 1., 1., 1.])

In [129]:
b = a.numpy()
b

array([1., 1., 1., 1., 1.], dtype=float32)

In [131]:
a = np.ones(5)
print(a)
b = torch.from_numpy(a)
print(b)

[1. 1. 1. 1. 1.]
tensor([1., 1., 1., 1., 1.], dtype=torch.float64)


# Autograd

In [174]:
x = torch.randn(3, requires_grad=True)
x

tensor([ 0.0973,  1.1226, -0.7198], requires_grad=True)

In [175]:
y = x + 2

In [176]:
y

tensor([2.0973, 3.1226, 1.2802], grad_fn=<AddBackward0>)

In [177]:
z = y*y*2
#z = z.mean()
z

tensor([ 8.7973, 19.5008,  3.2780], grad_fn=<MulBackward0>)

In [178]:
# z = z.mean() off we need to make v
v = torch.tensor([1, 2, 1], dtype=torch.float32)
z.backward(v)
print(x.grad)

tensor([ 8.3892, 24.9805,  5.1210])


In [182]:
weights = torch.ones(4, requires_grad=True)

for epoch in range(5):
    model_output = (weights * 3).sum()
    
    model_output.backward()
    
    print(weights.grad)
    
    weights.grad.zero_()

tensor([3., 3., 3., 3.])
tensor([3., 3., 3., 3.])
tensor([3., 3., 3., 3.])
tensor([3., 3., 3., 3.])
tensor([3., 3., 3., 3.])


# Backpropagation

In [189]:
x = torch.tensor(1.0)
y = torch.tensor(2.0)

w = torch.tensor(1.0, requires_grad=True)

# forward pass and compute the loss
y_hat = w * x
loss = (y_hat - y)**2

print(loss)

# Backward pass
loss.backward()
print(w.grad)

tensor(1., grad_fn=<PowBackward0>)
tensor(-2.)


# Gradient Descent

In [194]:
# f = w * x
# f = 2 * x

X = np.array([1, 2, 3, 4], dtype=np.float32)
Y = np.array([2, 4, 6, 8], dtype=np.float32)

w = 0.0

# model prediction
def forward(x):
    return w * x

# loss = MSE
def loss(y, y_predicted):
    return ((y_predicted-y)**2).mean()

# Gradient
# MSE = 1/N * (w*x - y)**2
# dJ/dw = 1/N 2x (w*x - y)
def gradient(x,y, y_predicted):
    return np.dot(2*x, y_predicted-y).mean()

print(f'Prediction before training: f(5) {forward(5):.3f}')

# Training
learning_rate = 0.01
n_iters = 20

for epoch in range(n_iters):
    # prediction =forward pass
    y_pred = forward(X)
    
    # loss
    l = loss(Y, y_pred)
    
    # Gradients
    dw = gradient(X,Y, y_pred)
    
    # Uptade weights
    w -= learning_rate * dw
    
    if epoch % 2 == 0:
        print(f'epoch{epoch+1}: w = {w:.3f}, loss = {l:.8f}')
        
print(f'Prediction after training: f(5) {forward(5):.3f}')


Prediction before training: f(5) 0.000
epoch1: w = 1.200, loss = 30.00000000
epoch3: w = 1.872, loss = 0.76800019
epoch5: w = 1.980, loss = 0.01966083
epoch7: w = 1.997, loss = 0.00050332
epoch9: w = 1.999, loss = 0.00001288
epoch11: w = 2.000, loss = 0.00000033
epoch13: w = 2.000, loss = 0.00000001
epoch15: w = 2.000, loss = 0.00000000
epoch17: w = 2.000, loss = 0.00000000
epoch19: w = 2.000, loss = 0.00000000
Prediction after training: f(5) 10.000
